language: node_js
# os: osx
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '12'
# Profundidad 3 versiones anteriores.
git:
  depth: 3
branches:
  except:
  - develop
  - jsvanilla
  - feature/header
  - feature/home-sidebar-booklist
  - feature/modall
  - travisCI
branches:
  only:
  - master
# before_install:
#   - python
install:
  -yarn install
script:
  - yarn build
  # - yarn test
  # - yarn deploy
# before_script:
#   - yastn test
jobs:
  include:
    - stage: test
      script: yarn test
      script: yarn eslint
    - stage: deploy
      script: yarn deploy
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  # Set in the setting page of your repository, as a secure variable
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master